### ISSUE TITLE
print doesnt work inside debugger

### ISSUE THREAD

**Issue by mbrain** [zarat/ScriptStack#1]
when i use stackshell it works, but not inside the debugger

**Comment by zarat** [comment]
The print function from the Std plugin writes to stdout, you dont want this in the debugger so there is a special function called "debug".

When you want to print something to the debugger output panel use "debug(string)"

**Comment by zarat** [comment]
`print` schreibt nach `stdout`, das will man im debugger wohl kaum. Es gibt eine eigene Funktion `debug` die genau wie `print` aufgerufen wird.
