### ISSUE TITLE
Variablen werden überschrieben

### ISSUE THREAD

**Issue by mbrain** [zarat/ScriptStack#5]
Ich erstelle 2 Arrays und wenn ich `print(Array1 + Array2)` aufrufe wird `array1` zu `Array1 + Array2`. Der Funktionsaufruf alleine sollte die Variablen doch aber nicht ändern sondern eine temporäre Variable erzeugen, oder?

```
function main() {

    var a = [1, 2, 3];
    var b = [4, 5, 6];    
    
    print(a + b);
    
    print("\n"); 
    
    print(a);
    
    print("\n"); 
    
    print(b);

}
```
Als Ergebnis bekomme ich folgendes

<pre>
D:\Projekte\ScriptStack-master\14\ScriptStack-master\StackShell\bin\debug>stackshell4 test.script
{ "0": "1", "1": "2", "2": "3", "3": "4", "4": "5", "5": "6" }
{ "0": "1", "1": "2", "2": "3", "3": "4", "4": "5", "5": "6" } // <- Sollte nicht sein
{ "0": "4", "1": "5", "2": "6" }
</pre>

Wenn ich das ganze mit Zahlen versuche geht es.

```
function main() {

    var a = 1;
    var b = 2;    
    
    print(a + b);
    
    print("\n"); 
    
    print(a);
    
    print("\n"); 
    
    print(b);

}
```

Das Ergebnis

<pre>
D:\Projekte\ScriptStack-master\14\ScriptStack-master\StackShell\bin\debug>stackshell4 test.script
3
1
2
</pre>

**Comment by zarat** [comment]
In `ScriptStack.Runtime.Context.ProcessArithmeticInstruction()` wird die Quelle direkt ins Ziel kopiert wenn es ein Array ist.

```CSharp
if (typeDest == typeof(ArrayList))
{
    ((ArrayList)objectValueDest).Add(objectValueSource);
    return;
}
```

Das alte Array sollte dabei nicht modifiziert werden indem am besten ein temporäres Array erzeugt und ins Ziel kopiert wird.

```CSharp
if (typeDest == typeof(ArrayList))
{
    ArrayList tmp = new ArrayList();
    tmp.Add((ArrayList)objectValueDest);
    tmp.Subtract(objectValueSource);
    AssignVariable(scriptInstruction.Operand0, tmp);
    return;
}
```

**Comment by zarat** [comment]
fixed in version 0.1.0.14
